#! /bin/sh

### BEGIN INIT INFO
# Provides:          lwzd 
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:		
# Short-Description: Heatpump connector daemon
### END INIT INFO

set -e

PIDFILE=/var/run/lwzd.pid
DAEMON=/usr/local/sbin/lwzd
ARGS="--daemonify"

test -x $DAEMON || exit 0

umask 022

. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Starting heatpump connector daemon" "lwzd" || true
	if start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON -- $ARGS; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
  stop)
	log_daemon_msg "Stopping heatpump connector daemon" "lwzd" || true
	if start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  restart)
	log_daemon_msg "Restarting heatpump connector daemon" "lwzd" || true
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
	if start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON -- $ARGS; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  status)
	status_of_proc -p $PIDFILE $DAEMON lwzd && exit 0 || exit $?
	;;

  *)
	log_action_msg "Usage: /etc/init.d/lwzd {start|stop|restart|status}" || true
	exit 1
esac

exit 0
